# Introdução a Numpy e Pandas
### Array


In [ ]:
import numpy as np 

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
matriz = np.array([[1.0,2],[3,4]])
matriz

array([[1., 2.],
       [3., 4.]])

In [23]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
print(matriz.shape)
print(tensor.shape)

(2, 2)
(2, 2, 2)


In [25]:
print(matriz.dtype)
print(tensor.dtype)

float64
int32


In [18]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
full = np.full((3,2),42)
full

array([[42, 42],
       [42, 42],
       [42, 42]])

### Aleatorio

In [53]:
np.random.rand(2, 3)

array([[0.45490846, 0.1245827 , 0.76373337],
       [0.87837161, 0.2226538 , 0.36051527]])

In [54]:
np.random.randint(0, 10, size=(2, 3))

array([[8, 2, 9],
       [2, 5, 6]])

### Indexação 

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 0]) # (linha 0, coluna 0)
print(a[0, 2]) # (linha 0, coluna 2)
print(a[-1, -1]) # (linha -1, coluna -1)

1
3
6


In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [34]:
print("Indexação 1:")
print(a[0:2, 1:3]) 
print("Indexação 2:")
print(a[:, 0:2]) 
print("Indexação 3:")
print(a[1, :]) 

Indexação 1:
[[2 3]
 [5 6]]
Indexação 2:
[[1 2]
 [4 5]]
Indexação 3:
[4 5 6]


In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

### Operações

In [44]:
print("sum:    ",a.sum())
print("max:    ",a.max())
print("min:    ",a.min())
print("media:  ",a.mean())
print("std:    ",a.std())
print("var:    ",a.var())

sum:     21
max:     6
min:     1
media:   3.5
std:     1.707825127659933
var:     2.9166666666666665


### Pandas

In [50]:
arr = np.array(range(10,20))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
pd.Series(arr)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [45]:
import pandas as pd
mat = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(mat)
df

0  1  2
0  1  2  3
1  4  5  6

In [48]:
df = pd.DataFrame(mat, columns=['col1','col2','col3'])
df

col1  col2  col3
0     1     2     3
1     4     5     6