# Introdução a Numpy e Pandas
## Exercicios em Sala

1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.


In [1]:
import numpy as np

arr = np.random.randint(0, 100, size=10)

print(arr)
print(arr.dtype)

[80 86  4 11 22 46 47 94 99 99]
int32


2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [4]:
import numpy as np

mat = np.random.rand(5, 5)

print(f"Valor mínimo: {np.min(mat)}")
print(f"Valor máximo: {np.max(mat)}")
print(f"Média: {np.average(mat)}")

Valor mínimo: 0.03683972656287793
Valor máximo: 0.9529549307917393
Média: 0.4931162323006273


3. Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [6]:
import numpy as np

arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)

print(arr)
print(arr_int)

[0.32083837 0.26041465 0.9324493  0.92940329 0.24248298 0.91552786
 0.80551202 0.30810261 0.98684727 0.78537575]
[3 2 9 9 2 9 8 3 9 7]


4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [7]:
import numpy as np

mat = np.random.randint(0, 10, (3, 3))

mat[1, :] = -1

print(mat)

[[ 0  0  5]
 [-1 -1 -1]
 [ 0  6  2]]


5. Crie um DataFrame com as seguintes informações:
 - Coluna "fruta": "Banana", "Maça", "Pera"
 - Coluna "preco": 7.90, 10.20, 11.80
 - Coluna "quantidade": 12, 3, 4


In [14]:
data = {"fruta": ["Banana", "Maça", "Pera"],
        "preco": [7.90, 10.20, 11.80],
        "quantidade": [12, 3, 4]}

df = pd.DataFrame([["Banana", 7.90, 12],
                   ["Maça", 10.20, 3],
                   ["Pera", 11.80, 4]],
                   columns = ['fruta','preco','quantidade'])
df


fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4

In [15]:
data = {"fruta": ["Banana", "Maça", "Pera"],
        "preco": [7.90, 10.20, 11.80],
        "quantidade": [12, 3, 4]}

df = pd.DataFrame(data)
df


fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4